### ISSUE TITLE
Generalize error handling

### ISSUE THREAD

**Issue by Neoyx** [Teamprojekt-Lagersystem/Lagersystem-Backend#20]
Exception in the backend should be handled so that the frontend is aware of every error that occurs.

**Comment by Neoyx** [comment]
ToDo:

- [ ] onDelete=Cascade bei Storage scheint noch nicht ganz zu funktionieren ==> Child wird nicht mit gelöscht
- [ ] ApiResponse.Error zu einer Liste an Fehlern machen, sodass auch mehrere Inputs falsch sein können (Später für Validierung wichtig)

**Comment by lumeav** [comment]
Falls mehrere Fehler falsch sein können bspw. badRequest und ein notFound error, welchen HttpStatusCode geben wir zurück wenn wir mehrere Fehler gleichzeitig zurückgeben?

**Comment by lumeav** [comment]
> Falls mehrere Fehler falsch sein können bspw. badRequest und ein notFound error, welchen HttpStatusCode geben wir zurück wenn wir mehrere Fehler gleichzeitig zurückgeben?

Es wurde entschieden, dass immer ein badRequest StatusCode zurückgegeben wird, egal bei welchem Fehler
