### ISSUE TITLE
Cascade on Delete of Entitites

### ISSUE THREAD

**Issue by Neoyx** [Teamprojekt-Lagersystem/Lagersystem-Backend#23]
Wenn ein Storage gelöscht wird, sollten all seine child storages ebenfalls gelöscht werden. Dazu kann "onDelete=Cascade" genutzt werden bei Definierung der Referenzen. 

Aktuell scheint es noch nicht ganz zu funktionieren. Ebenfalls sollte onDelete=Cascade für Spaces konfiguriert sein, sodass spaces in einem storage mit diesem zusammen gelöscht werden ==> Siehe #20 

@JonasSeifried gerne nochmal zusammen anschauen

**Comment by lumeav** [comment]
fixed in #27
