### ISSUE TITLE
Angabe der Rekursionstiefe bei getStorages()

### ISSUE THREAD

**Issue by Neoyx** [Teamprojekt-Lagersystem/Lagersystem-Backend#24]
Ziel ist es über einen Parameter die Rekursionstiefe bei getStorages anzugeben

**Comment by dennishoang** [comment]
Es ist nun möglich die Rekursionstiefe für get storage/storages anzugeben mit einen optionalen parameter depth. Falls der optionale Parameter nicht angegeben wird, gibt die Route per Default eine Tiefe von 3 aus.

Bitte Abstimmung welche Standardmäßige Tiefe,  gewählt werden soll wenn der Parameter nicht angegeben wird.

**Comment by lumeav** [comment]
Ich finde 3 ist in Ordnung

**Comment by Neoyx** [comment]
Todo: 
- [ ]  Wenn man eine eigene Tiefe angibt, wird trotzdem maximal immer die Tiefe 3 genommen. Bei Eingabe eigener Tiefe sollte die default Tiefe nicht die Grenze sein. @dennishoang

![Image](https://github.com/user-attachments/assets/44e40c0b-79ff-475c-9663-0b640a7d3562)

Hier wird bspw. bei Angabe von Tiefe 4 trotzdem Tiefe 3 als max. genommen.
