### ISSUE TITLE
fix and extend tests

### ISSUE THREAD

**Issue by JonasSeifried** [Teamprojekt-Lagersystem/Lagersystem-Backend#26]

**Comment by Neoyx** [comment]
Schreibe fehlende Tests für:

- [ ] Product (?)
- [ ] StorageRepository
- [ ] StorageRoutes
- [ ] SpaceRepository
- [ ] SpaceRoutes

==> Gerne hinter einem Task eintragen, sodass man sieht wer welche Tests macht
