### ISSUE TITLE
create util class for the use of multiple repositories

### ISSUE THREAD

**Issue by dennishoang** [Teamprojekt-Lagersystem/Lagersystem-Backend#51]
for the use of the endpoint move children we need to use multiple repositories. therefore a new util class is needed for the endpoints

**Comment by Neoyx** [comment]
Create a higher level of abstraction for the use of multiple repositories. In this level of abstraction, only the functions of the repositories should be used, no entities anymore. Missing functions need to be implemented

**Comment by lumeav** [comment]
It has been decided that this is no longer needed excessively, which is why this issue will be closed. However, it may be reopened in the future if necessary.
