### ISSUE TITLE
Store date of creation for storage, space and product

### ISSUE THREAD

**Issue by Neoyx** [Teamprojekt-Lagersystem/Lagersystem-Backend#69]
When a storage, space or product is being created, the date of creation should be stored.

**Comment by JonasSeifried** [comment]
Should also store `updatedAt`

**Comment by Neoyx** [comment]
<img width="549" alt="Image" src="https://github.com/user-attachments/assets/a472948a-2791-40e2-abe6-9b091fd082a2" />

Additionally I specified a default value as the current DateTime. This is required for batch inserts in the tests. The default value is only being used if there is no DateTime specified when an object is inserted into the table (which typically does not occur, but batch inserts rely on defaults).

**Comment by Neoyx** [comment]
I also specified a defaultExpression for the updateAt attribute, which contains the timestamp on which the object has been updated the last time.

<img width="514" alt="Image" src="https://github.com/user-attachments/assets/991c8323-7896-4bcb-92e3-fad192c47ec5" />

Initially, when an object is created, the update and create timestamp are the same. So to check if an object has never been updated before, just check if the timestamps of update and create are equal.

**Comment by Neoyx** [comment]
Zusammenfassung:
- Die timestamps **_creationTime_** und **_updatedAt_** sind bei der Objekterstellung gleich
- Für beide timestamps gibt es einen default wert um batch inserting zu ermögichen (für Tests)
- Die precision wurde auf Mikrosekunden gestellt damit die Tests keine Probleme machen
- **_updatedAt_** wird sowohl bei update() als auch move() neu gesetzt

**Comment by Neoyx** [comment]
I have tried using the "subscriber" approach (subscribe to changes on an object and update the "updatedAt" timestamp), but then the returned object of the update-function does not include the updated timestamp already, because the database updates it in the background. That's why I keep updating the timestamp manually in every function that updates an attribute of an object, but in the future we might implement the subscriber if we have too much update functions. @JonasSeifried
